sonar.projectKey=lbr1014_TFG_RAG
sonar.organization=lbr1014


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=TFG_RAG
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app/normativa_UBU/app/main,app/normativa_UBU/docker,app/normativa_UBU/docker-compose.yml

# Tests de la app
sonar.tests=app/normativa_UBU/app/test

# Excluir basura
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/venv/**,**/.pytest_cache/**,**/.ruff_cache/**,**/migrations/**,**/static/**,**/templates/**

# Excluir tests de cobertura
sonar.coverage.exclusions=app/normativa_UBU/app/test/**

# Cobertura
sonar.python.coverage.reportPaths=app/normativa_UBU/coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.python.version=3.10
