"""create_table_documentos

Revision ID: c8c13480f8d8
Revises: b63c4b123c37
Create Date: 2026-01-23 00:40:57.207267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c8c13480f8d8'
down_revision = 'b63c4b123c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chunks', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_hash'), ['hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_modified_at'), ['modified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_nombre'), ['nombre'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.drop_table('_alembic_tmp_consultas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_consultas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pregunta', sa.TEXT(), nullable=False),
    sa.Column('respuesta', sa.TEXT(), nullable=False),
    sa.Column('fragmentos', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('tiempo_respuestas', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_nombre'))
        batch_op.drop_index(batch_op.f('ix_documents_modified_at'))
        batch_op.drop_index(batch_op.f('ix_documents_hash'))

    op.drop_table('documents')
    # ### end Alembic commands ###
